apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc-1
spec:
  accessModes:
  # 需要使用和 PV 一致的访问模式
  - ReadWriteMany
  # 按需分配资源
  resources:
     requests:
       storage: 5Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-pvc-2
spec:
  accessModes:
  # 需要使用和 PV 一致的访问模式
  - ReadWriteMany
  # 按需分配资源
  resources:
     requests:
       storage: 1Gi
