apiVersion: v1
kind: Secret
metadata:
  name: ceph-secret-admin
  namespace: kube-system
type: "kubernetes.io/rbd"  
data:
  key: QVFCb0Z4MWV2UVhhQ0JBQWgvS3VwMnMxY09GWTlPSjBQMXpkOWc9PQ==

---

apiVersion: v1
kind: Secret
metadata:
  name: ceph-secret-kubeuser1
  namespace: default
type: "kubernetes.io/rbd"  
data:
# ceph auth get-key client.kubeuser1 | base64
  key: QVFBS2FDcGVqSE5YTlJBQTJ1ZHdwaEErblRUS2ZJVGxPZG9HclE9PQ==