apiVersion: v1
kind: PersistentVolume
metadata:
  name: ceph-fs-pv3
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  cephfs:
    monitors:
      - 10.184.101.245:6789
      - 10.184.101.246:6789
      - 10.184.101.247:6789
    user: admin
    secretRef: 
      name: ceph-secret-admin # 貌似只能在default namespace
    readOnly: false
  # persistentVolumeReclaimPolicy: Recycle 测试下来删除pvc时该pv会报错，说没有recycle plugin
