apiVersion: v1
kind: Pod
metadata:
  name: ceph-rbd-pod
  labels:
    name: ceph-rbd-pod
spec:
  containers:
  - name: ceph-rbd-pod
    image: busybox
    command: ["sleep", "60000"]
    volumeMounts:
      - name: ceph-rbd-vol1
        mountPath: /mnt
        readOnly: false
    resources:
      limits:
        memory: "128Mi"
        cpu: "50m"
  volumes:
    - name: ceph-rbd-vol1
      persistentVolumeClaim:
        claimName: ceph-rbd-pvc
