apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ceph-rbd-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ceph-pool1
  resources:
    requests:
      storage: 1Gi

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ceph-rbd-pvc2
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ceph-pool1
  resources:
    requests:
      storage: 2Gi