# https://kubernetes.io/zh/docs/concepts/workloads/controllers/statefulset/
apiVersion: v1
kind: Service
metadata:
  name: nginx-sts-fs
  labels:
    app: nginx-sts-fs
spec:
  ports:
  - port: 80
    name: web
  clusterIP: None
  selector:
    app: nginx-sts-fs
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: web-cephfs
spec:
  selector:
    matchLabels:
      app: nginx-sts-fs # has to match .spec.template.metadata.labels
  serviceName: "nginx-sts-fs"
  replicas: 3 # by default is 1
  template:
    metadata:
      labels:
        app: nginx-sts-fs # has to match .spec.selector.matchLabels
    spec:
      terminationGracePeriodSeconds: 10
      # nodeSelector:
      #   kubernetes.io/hostname: infra-node2
      containers:
      - name: nginx
        image: google-containers/nginx-slim:0.8
        ports:
        - containerPort: 80
          name: web
        volumeMounts:
        - name: www
          mountPath: /usr/share/nginx/html
  volumeClaimTemplates:
  - metadata:
      name: www
    spec:
      accessModes: [ "ReadWriteMany" ]
      storageClassName: "mycephfs"
      resources:
        requests:
          storage: 1Gi
