kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: mycephfs
provisioner: ceph.com/cephfs
parameters:
    monitors: 10.184.101.245:6789,10.184.101.246:6789,10.184.101.247:6789 # 经测试不能用主机名，只能用ip
    adminId: admin
    adminSecretName: ceph-secret-admin
    adminSecretNamespace: "cephfs"
    claimRoot: /pvc-volumes