apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ceph-pool1
provisioner: ceph.com/rbd
parameters:
  monitors: 10.184.101.245:6789,10.184.101.246:6789,10.184.101.247:6789 # 经测试不能用主机名，只能用ip
  adminId: admin
  adminSecretName: ceph-secret-admin
  adminSecretNamespace: kube-system
  pool: ceph-pool1
  userId: kubeuser1
  userSecretName: ceph-secret-kubeuser1
  userSecretNamespace: default
  fsType: ext4
  imageFormat: "2"
  imageFeatures: "layering"
